source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-theme-minimal"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "webrick" # Required for Ruby 3+

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-redirect-from"
end